### ISSUE TITLE
Geomesa quickstart turorial

### ISSUE THREAD

**Issue by pvinchon** [geodocker/geodocker-accumulo-geomesa#17]
Hi,

I am trying to follow the [geomesa quick start tutorial from geomesa](https://github.com/geomesa/geomesa-tutorials/tree/master/geomesa-quickstart-accumulo), but I can't seem to be able to connect.

When I run their quick start I encounter the following error
```
java -cp geomesa-quickstart-accumulo/target/geomesa-quickstart-accumulo-*.jar \
  com.example.geomesa.accumulo.AccumuloQuickStart \
  -instanceId accumulo \
  -zookeepers localhost \
  -user root \
  -password GisPwd \
  -tableName mynamespace.mytable
Loading Config Defaults.
Failed to open transport to f71417047199:9997
Failed to find an available server in the list of servers: [f71417047199:9997 (120000)]
Failed to open transport to f71417047199:9997
Failed to open transport to f71417047199:9997
^C
```

Zookeeper raises the following warning when I stop the quickstart
```
zookeeper_1         | 2016-12-11 17:36:31,773 [myid:] - WARN  [NIOServerCxn.Factory:0.0.0.0/0.0.0.0:2181:NIOServerCnxn@357] - caught end of stream exception
zookeeper_1         | EndOfStreamException: Unable to read additional data from client sessionid 0x158eef0d3fb000e, likely client has closed socket
zookeeper_1         | 	at org.apache.zookeeper.server.NIOServerCnxn.doIO(NIOServerCnxn.java:230)
zookeeper_1         | 	at org.apache.zookeeper.server.NIOServerCnxnFactory.run(NIOServerCnxnFactory.java:203)
zookeeper_1         | 	at java.lang.Thread.run(Thread.java:745)
```

Would it be wrong credentials [root / GisPwd] ?

**Comment by jbkoh** [comment]
Not sure if this repository is alive, but I got the same issue. I'd appreciate if I got some answer for it.
Thanks!
